[package]
name = "apob-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
apob.workspace = true
clap.workspace = true
crossterm.workspace = true
ratatui.workspace = true
strum.workspace = true
strum_macros.workspace = true
zerocopy.workspace = true
